CREATE TABLE CONTACT
(
    CONTACT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTACT_NAME VARCHAR(100) NOT NULL,
    CONTACT_EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT UC_EMAIL UNIQUE (CONTACT_EMAIL)
);